FROM node:alpine

ENV MYSQL_ROOT_PASSWORD=yahewaai
ENV MYSQL_PORT=3306
ENV MYSQL_ROOT_HOST=172.18.0.22
ENV MYSQL_USER=root
ENV MYSQL_CHARSET=utf8
ENV MYSQL_TIMEZONE=local
ENV MYSQL_PORT=10073

RUN apk update
RUN apk add zip
RUN apk add unzip
RUN apk add nodejs

WORKDIR /api

COPY ./api /api
COPY ./api/tsconfig.json /api
COPY ./api/package.json /api

RUN rm -fr dist
RUN npm install
# RUN cd /api && npx tsc && node dist/index.js
RUN npx tsc
CMD ["node", "dist/index.js"]

EXPOSE 80
EXPOSE 10073